import type { FullFact } from '@/types/fact';

export const COMPREHENSIVE_SAMPLE_FACTS: FullFact[] = [
  // 🚀 Space & Astronomy Facts (4 facts)
  {
    id: 'galactic-ocean-1',
    title: "Saturn's moon Enceladus contains hydrothermal vents",
    summary: 'Cassini data suggests warm hydrothermal activity consistent with silica nanoparticles found in plumes.',
    fullContent: 'Cassini flybys detected silica nanoparticles in the plume of Enceladus. Their composition and size imply they formed in warm hydrothermal environments beneath the icy crust, suggesting liquid water pockets heated by tidal forces.',
    sources: ['https://saturn.jpl.nasa.gov/resources/7038/enceladus-hydrothermal-activity/'],
    metadata: {
      created: new Date('2024-06-01T12:00:00Z'),
      lastModified: new Date('2024-07-15T09:30:00Z'),
      version: 1,
      contentType: 'text/plain',
      tags: [
        { name: 'space', category: 'topic' },
        { name: 'astronomy', category: 'topic' },
        { name: 'verified', category: 'methodology' },
        { name: 'hydrothermal', category: 'type' },
        { name: 'saturn', category: 'type' },
        { name: 'cassini', category: 'type' }
      ],
    },
    status: 'verified',
    votes: 1243,
    comments: 89,
    author: 'anon-4f8c',
    updated: '2h ago',
    walrusBlobId: undefined,
    contentHash: undefined,
  },
  {
    id: 'alpha-centauri-2',
    title: 'No confirmed exoplanets yet in Alpha Centauri AB system',
    summary: 'Claims of planet discovery lack peer-reviewed verification despite ongoing search campaigns.',
    fullContent: 'Despite frequent rumors, no statistically significant exoplanet detection has been published for the Alpha Centauri AB binary system. Proxima Centauri b (2016) remains the only confirmed planet in the system. Current radial velocity surveys continue monitoring for planetary signatures.',
    sources: ['https://www.eso.org/public/news/eso1629/', 'https://arxiv.org/abs/1609.03449'],
    metadata: {
      created: new Date('2024-06-21T10:00:00Z'),
      lastModified: new Date('2024-08-02T11:15:00Z'),
      version: 1,
      contentType: 'text/plain',
      tags: [
        { name: 'space', category: 'topic' },
        { name: 'exoplanets', category: 'type' },
        { name: 'verification', category: 'methodology' },
        { name: 'alpha-centauri', category: 'type' },
        { name: 'radial-velocity', category: 'type' }
      ],
    },
    status: 'review',
    votes: 312,
    comments: 45,
    author: 'anon-a21e',
    updated: '6h ago',
    walrusBlobId: undefined,
    contentHash: undefined,
  },
  {
    id: 'james-webb-infrared-3',
    title: 'James Webb Space Telescope detects water vapor in rocky exoplanet atmosphere',
    summary: 'JWST spectroscopy confirms atmospheric water on WASP-96b, demonstrating new capabilities for exoplanet characterization.',
    fullContent: 'The James Webb Space Telescope has successfully detected water vapor signatures in the atmosphere of the hot gas giant WASP-96b using transmission spectroscopy. This marks a significant milestone in exoplanet atmospheric characterization, with implications for studying potentially habitable worlds.',
    sources: ['https://www.nasa.gov/news/releases/2022/nasa-s-webb-delivers-deepest-infrared-image-of-universe-yet'],
    metadata: {
      created: new Date('2024-08-10T16:20:00Z'),
      lastModified: new Date('2024-08-10T16:20:00Z'),
      version: 1,
      contentType: 'text/plain',
      tags: [
        { name: 'space', category: 'topic' },
        { name: 'jwst', category: 'type' },
        { name: 'exoplanet', category: 'type' },
        { name: 'water-vapor', category: 'type' },
        { name: 'spectroscopy', category: 'methodology' },
        { name: 'verified', category: 'methodology' }
      ],
    },
    status: 'verified',
    votes: 892,
    comments: 67,
    author: 'anon-jwst1',
    updated: '3d ago',
    walrusBlobId: undefined,
    contentHash: undefined,
  },
  {
    id: 'mars-methane-4',
    title: 'Seasonal methane variations on Mars remain unexplained',
    summary: 'Curiosity rover data shows cyclical methane spikes, but the source mechanism is still debated among researchers.',
    fullContent: 'NASA\'s Curiosity rover has detected seasonal variations in atmospheric methane on Mars, with concentrations rising in northern summer. While this suggests active methane sources, the exact mechanism remains unclear. Possibilities include geological processes, subsurface microbes, or UV-driven chemistry.',
    sources: ['https://science.nasa.gov/missions/mars-science-laboratory/curiosity-rover/', 'https://doi.org/10.1126/science.aay3326'],
    metadata: {
      created: new Date('2024-07-25T11:30:00Z'),
      lastModified: new Date('2024-07-25T11:30:00Z'),
      version: 1,
      contentType: 'text/plain',
      tags: [
        { name: 'space', category: 'topic' },
        { name: 'mars', category: 'type' },
        { name: 'methane', category: 'type' },
        { name: 'curiosity', category: 'type' },
        { name: 'seasonal', category: 'type' },
        { name: 'mystery', category: 'type' }
      ],
    },
    status: 'flagged',
    votes: 567,
    comments: 91,
    author: 'anon-mars1',
    updated: '1w ago',
    walrusBlobId: undefined,
    contentHash: undefined,
  },

  // 🌍 Climate & Environment Facts (4 facts)
  {
    id: 'arctic-ice-5',
    title: 'Arctic sea ice decline accelerating beyond climate model predictions',
    summary: 'Satellite measurements show Arctic ice loss rates exceed most IPCC projections, with implications for global climate feedback.',
    fullContent: 'Arctic sea ice extent has declined at approximately 13% per decade since 1979, faster than predicted by many climate models. This accelerated loss reduces Earth\'s albedo, creating positive feedback loops that may accelerate warming. Multi-year ice is particularly vulnerable.',
    sources: ['https://nsidc.org/learn/ask-scientist/arctic-sea-ice-decline', 'https://doi.org/10.1038/s41558-019-0662-y'],
    metadata: {
      created: new Date('2024-08-01T14:15:00Z'),
      lastModified: new Date('2024-08-01T14:15:00Z'),
      version: 1,
      contentType: 'text/plain',
      tags: [
        { name: 'climate', category: 'topic' },
        { name: 'arctic', category: 'region' },
        { name: 'sea-ice', category: 'type' },
        { name: 'satellite', category: 'methodology' },
        { name: 'feedback', category: 'type' },
        { name: 'urgent', category: 'urgency' }
      ],
    },
    status: 'verified',
    votes: 1456,
    comments: 203,
    author: 'anon-clim1',
    updated: '4d ago',
    walrusBlobId: undefined,
    contentHash: undefined,
  },
  {
    id: 'ocean-acidification-6',
    title: 'Ocean pH has dropped 0.1 units since pre-industrial times',
    summary: 'Seawater acidification from CO2 absorption threatens marine ecosystems and calcium carbonate shell formation.',
    fullContent: 'The ocean has absorbed approximately 30% of anthropogenic CO2 emissions, leading to a 0.1 unit decrease in pH since 1750. This represents a 26% increase in hydrogen ion concentration. Shell-forming organisms like corals, mollusks, and some plankton face increased dissolution rates.',
    sources: ['https://www.noaa.gov/education/resource-collections/ocean-coasts/ocean-acidification', 'https://doi.org/10.1146/annurev-marine-121211-172339'],
    metadata: {
      created: new Date('2024-07-30T10:45:00Z'),
      lastModified: new Date('2024-07-30T10:45:00Z'),
      version: 1,
      contentType: 'text/plain',
      tags: [
        { name: 'climate', category: 'topic' },
        { name: 'ocean', category: 'type' },
        { name: 'acidification', category: 'type' },
        { name: 'co2', category: 'type' },
        { name: 'marine', category: 'type' },
        { name: 'critical', category: 'urgency' }
      ],
    },
    status: 'verified',
    votes: 987,
    comments: 134,
    author: 'anon-ocean1',
    updated: '5d ago',
    walrusBlobId: undefined,
    contentHash: undefined,
  },
  {
    id: 'permafrost-methane-7',
    title: 'Permafrost thaw releasing methane faster than expected',
    summary: 'Arctic permafrost degradation is accelerating methane emissions, potentially creating runaway warming feedback.',
    fullContent: 'Thawing permafrost in the Arctic is releasing both CO2 and methane at accelerating rates. Methane emissions are particularly concerning due to their 25x warming potential compared to CO2. Some regions show methane release rates 5x higher than previous estimates.',
    sources: ['https://www.nature.com/articles/s41467-021-27439-6', 'https://doi.org/10.1038/s41467-021-27439-6'],
    metadata: {
      created: new Date('2024-08-05T09:20:00Z'),
      lastModified: new Date('2024-08-05T09:20:00Z'),
      version: 1,
      contentType: 'text/plain',
      tags: [
        { name: 'climate', category: 'topic' },
        { name: 'permafrost', category: 'type' },
        { name: 'methane', category: 'type' },
        { name: 'arctic', category: 'region' },
        { name: 'feedback', category: 'type' },
        { name: 'urgent', category: 'urgency' }
      ],
    },
    status: 'flagged',
    votes: 743,
    comments: 156,
    author: 'anon-perm1',
    updated: '2d ago',
    walrusBlobId: undefined,
    contentHash: undefined,
  },
  {
    id: 'coral-bleaching-8',
    title: 'Great Barrier Reef experiences unprecedented back-to-back bleaching events',
    summary: 'Consecutive mass bleaching events in 2016-2017 and 2020-2022 indicate accelerating thermal stress on coral ecosystems.',
    fullContent: 'The Great Barrier Reef has experienced multiple consecutive mass bleaching events, with 2016, 2017, 2020, and 2022 showing severe thermal stress. This unprecedented frequency prevents coral recovery and threatens ecosystem collapse. Water temperatures 1-2°C above normal trigger bleaching.',
    sources: ['https://www.gbrmpa.gov.au/the-reef/reef-health', 'https://doi.org/10.1038/s41586-017-0305-4'],
    metadata: {
      created: new Date('2024-07-20T13:10:00Z'),
      lastModified: new Date('2024-07-20T13:10:00Z'),
      version: 1,
      contentType: 'text/plain',
      tags: [
        { name: 'climate', category: 'topic' },
        { name: 'coral', category: 'type' },
        { name: 'bleaching', category: 'type' },
        { name: 'reef', category: 'type' },
        { name: 'thermal-stress', category: 'type' },
        { name: 'critical', category: 'urgency' }
      ],
    },
    status: 'verified',
    votes: 1234,
    comments: 187,
    author: 'anon-coral1',
    updated: '1w ago',
    walrusBlobId: undefined,
    contentHash: undefined,
  },

  // 🤖 AI & Technology Facts (4 facts)
  {
    id: 'llm-reasoning-9',
    title: 'Large language models show emergent reasoning abilities at scale',
    summary: 'GPT-3 and later models demonstrate complex reasoning that emerges only at sufficient parameter counts and training data.',
    fullContent: 'Large language models above ~100B parameters exhibit emergent abilities not present in smaller versions, including multi-step reasoning, analogical thinking, and in-context learning. These capabilities appear suddenly at scale thresholds rather than gradually improving.',
    sources: ['https://arxiv.org/abs/2206.07682', 'https://doi.org/10.48550/arXiv.2206.07682'],
    metadata: {
      created: new Date('2024-08-08T15:30:00Z'),
      lastModified: new Date('2024-08-08T15:30:00Z'),
      version: 1,
      contentType: 'text/plain',
      tags: [
        { name: 'ai', category: 'topic' },
        { name: 'llm', category: 'type' },
        { name: 'reasoning', category: 'type' },
        { name: 'emergent', category: 'type' },
        { name: 'scale', category: 'type' },
        { name: 'experimental', category: 'methodology' }
      ],
    },
    status: 'review',
    votes: 567,
    comments: 89,
    author: 'anon-ai1',
    updated: '1d ago',
    walrusBlobId: undefined,
    contentHash: undefined,
  },
  {
    id: 'quantum-advantage-10',
    title: 'Google Sycamore achieves quantum computational advantage',
    summary: 'Quantum processor solved sampling problem in 200 seconds that would take classical supercomputer 10,000 years.',
    fullContent: 'Google\'s 53-qubit Sycamore processor performed random circuit sampling in 200 seconds, while the equivalent calculation would require 10,000 years on Summit supercomputer. However, debate continues over practical applications and IBM\'s challenge to the classical baseline.',
    sources: ['https://www.nature.com/articles/s41586-019-1666-5', 'https://doi.org/10.1038/s41586-019-1666-5'],
    metadata: {
      created: new Date('2024-07-12T11:00:00Z'),
      lastModified: new Date('2024-07-12T11:00:00Z'),
      version: 1,
      contentType: 'text/plain',
      tags: [
        { name: 'technology', category: 'topic' },
        { name: 'quantum', category: 'type' },
        { name: 'computing', category: 'type' },
        { name: 'advantage', category: 'type' },
        { name: 'sycamore', category: 'type' },
        { name: 'peer-reviewed', category: 'methodology' }
      ],
    },
    status: 'verified',
    votes: 892,
    comments: 124,
    author: 'anon-quantum1',
    updated: '2w ago',
    walrusBlobId: undefined,
    contentHash: undefined,
  },
  {
    id: 'protein-folding-11',
    title: 'AlphaFold predicts protein structures with atomic accuracy',
    summary: 'DeepMind\'s AI system solved protein folding problem, predicting 3D structures for over 200 million proteins.',
    fullContent: 'AlphaFold2 achieved atomic-level accuracy in protein structure prediction, solving a 50-year grand challenge in biology. The system combines attention mechanisms with physical constraints to predict folding patterns. Over 200 million protein structures are now freely available.',
    sources: ['https://www.nature.com/articles/s41586-021-03819-2', 'https://alphafold.ebi.ac.uk/'],
    metadata: {
      created: new Date('2024-07-28T14:20:00Z'),
      lastModified: new Date('2024-07-28T14:20:00Z'),
      version: 1,
      contentType: 'text/plain',
      tags: [
        { name: 'ai', category: 'topic' },
        { name: 'biology', category: 'topic' },
        { name: 'protein', category: 'type' },
        { name: 'folding', category: 'type' },
        { name: 'alphafold', category: 'type' },
        { name: 'breakthrough', category: 'type' }
      ],
    },
    status: 'verified',
    votes: 1567,
    comments: 234,
    author: 'anon-protein1',
    updated: '1w ago',
    walrusBlobId: undefined,
    contentHash: undefined,
  },
  {
    id: 'neural-scaling-12',
    title: 'Neural network performance scales predictably with compute',
    summary: 'Scaling laws show smooth power-law relationships between model size, data, compute, and performance across domains.',
    fullContent: 'Research reveals consistent scaling laws where neural network performance follows predictable power-law relationships with compute budget, dataset size, and parameter count. These scaling laws hold across language, vision, and other domains, enabling reliable performance forecasting.',
    sources: ['https://arxiv.org/abs/2001.08361', 'https://arxiv.org/abs/2203.15556'],
    metadata: {
      created: new Date('2024-08-03T10:15:00Z'),
      lastModified: new Date('2024-08-03T10:15:00Z'),
      version: 1,
      contentType: 'text/plain',
      tags: [
        { name: 'ai', category: 'topic' },
        { name: 'scaling', category: 'type' },
        { name: 'neural-networks', category: 'type' },
        { name: 'compute', category: 'type' },
        { name: 'power-law', category: 'type' },
        { name: 'theoretical', category: 'methodology' }
      ],
    },
    status: 'review',
    votes: 445,
    comments: 67,
    author: 'anon-scale1',
    updated: '4d ago',
    walrusBlobId: undefined,
    contentHash: undefined,
  },

  // 🧬 Medicine & Biology Facts (4 facts)
  {
    id: 'mrna-vaccine-13',
    title: 'mRNA vaccines demonstrate 95% efficacy against COVID-19',
    summary: 'Pfizer-BioNTech and Moderna vaccines showed unprecedented efficacy in Phase 3 trials using novel mRNA technology.',
    fullContent: 'mRNA vaccines achieved 94-95% efficacy in preventing symptomatic COVID-19 in large-scale clinical trials. This technology instructs cells to produce spike protein, triggering immune response without live virus. The rapid development timeline was enabled by prior mRNA research.',
    sources: ['https://www.nejm.org/doi/full/10.1056/NEJMoa2034577', 'https://www.nejm.org/doi/full/10.1056/NEJMoa2035389'],
    metadata: {
      created: new Date('2024-06-15T09:30:00Z'),
      lastModified: new Date('2024-06-15T09:30:00Z'),
      version: 1,
      contentType: 'text/plain',
      tags: [
        { name: 'medicine', category: 'topic' },
        { name: 'vaccine', category: 'type' },
        { name: 'mrna', category: 'type' },
        { name: 'covid19', category: 'type' },
        { name: 'clinical-trial', category: 'methodology' },
        { name: 'verified', category: 'methodology' }
      ],
    },
    status: 'verified',
    votes: 2134,
    comments: 345,
    author: 'anon-med1',
    updated: '3w ago',
    walrusBlobId: undefined,
    contentHash: undefined,
  },
  {
    id: 'crispr-efficiency-14',
    title: 'CRISPR gene editing shows improved precision with base editing',
    summary: 'Next-generation CRISPR tools enable single nucleotide changes without double-strand breaks, reducing off-target effects.',
    fullContent: 'Base editors and prime editors represent major advances in CRISPR technology, allowing precise single-nucleotide changes without creating double-strand breaks. These tools reduce unwanted insertions and deletions while enabling correction of point mutations causing genetic diseases.',
    sources: ['https://www.nature.com/articles/s41586-019-1711-4', 'https://doi.org/10.1038/s41586-019-1711-4'],
    metadata: {
      created: new Date('2024-07-05T16:45:00Z'),
      lastModified: new Date('2024-07-05T16:45:00Z'),
      version: 1,
      contentType: 'text/plain',
      tags: [
        { name: 'biology', category: 'topic' },
        { name: 'crispr', category: 'type' },
        { name: 'gene-editing', category: 'type' },
        { name: 'base-editing', category: 'type' },
        { name: 'precision', category: 'type' },
        { name: 'peer-reviewed', category: 'methodology' }
      ],
    },
    status: 'verified',
    votes: 876,
    comments: 123,
    author: 'anon-crispr1',
    updated: '2w ago',
    walrusBlobId: undefined,
    contentHash: undefined,
  },
  {
    id: 'longevity-drugs-15',
    title: 'Rapamycin extends lifespan in multiple animal models',
    summary: 'mTOR inhibitor shows consistent life extension effects across species, but human applications remain under investigation.',
    fullContent: 'Rapamycin, an mTOR pathway inhibitor, has extended lifespan by 10-30% in mice, flies, and worms. The drug appears to delay aging by reducing cellular senescence and improving autophagy. Human longevity trials are ongoing but face challenges with immune suppression side effects.',
    sources: ['https://www.nature.com/articles/nature08221', 'https://doi.org/10.1038/nature08221'],
    metadata: {
      created: new Date('2024-08-01T12:00:00Z'),
      lastModified: new Date('2024-08-01T12:00:00Z'),
      version: 1,
      contentType: 'text/plain',
      tags: [
        { name: 'medicine', category: 'topic' },
        { name: 'longevity', category: 'type' },
        { name: 'rapamycin', category: 'type' },
        { name: 'mtor', category: 'type' },
        { name: 'aging', category: 'type' },
        { name: 'experimental', category: 'methodology' }
      ],
    },
    status: 'review',
    votes: 654,
    comments: 198,
    author: 'anon-aging1',
    updated: '6d ago',
    walrusBlobId: undefined,
    contentHash: undefined,
  },
  {
    id: 'organoids-modeling-16',
    title: 'Brain organoids reproduce key aspects of human neurodevelopment',
    summary: '3D brain models grown from stem cells recapitulate cortical development and disease phenotypes in vitro.',
    fullContent: 'Cerebral organoids grown from human pluripotent stem cells successfully model key aspects of brain development including neurogenesis, migration, and synaptogenesis. These "mini-brains" enable study of human-specific neurodevelopmental disorders and drug testing without animal models.',
    sources: ['https://www.nature.com/articles/nature12517', 'https://doi.org/10.1038/nature12517'],
    metadata: {
      created: new Date('2024-07-18T14:30:00Z'),
      lastModified: new Date('2024-07-18T14:30:00Z'),
      version: 1,
      contentType: 'text/plain',
      tags: [
        { name: 'biology', category: 'topic' },
        { name: 'organoids', category: 'type' },
        { name: 'brain', category: 'type' },
        { name: 'stem-cells', category: 'type' },
        { name: 'development', category: 'type' },
        { name: 'in-vitro', category: 'methodology' }
      ],
    },
    status: 'verified',
    votes: 789,
    comments: 156,
    author: 'anon-brain1',
    updated: '10d ago',
    walrusBlobId: undefined,
    contentHash: undefined,
  },

  // ⚛️ Physics & Materials Facts (3 facts)
  {
    id: 'room-temp-superconductor-17',
    title: 'Claims of room-temperature superconductor remain unverified',
    summary: 'Recent preprints claiming ambient superconductivity have failed independent replication attempts.',
    fullContent: 'Multiple research groups have attempted to replicate claims of room-temperature, ambient-pressure superconductivity in copper-substituted lead apatite (LK-99). Initial results show no evidence of superconductivity, with observed phenomena explained by conventional physics and measurement artifacts.',
    sources: ['https://arxiv.org/abs/2307.12008', 'https://arxiv.org/abs/2308.01192'],
    metadata: {
      created: new Date('2024-08-15T10:20:00Z'),
      lastModified: new Date('2024-08-15T10:20:00Z'),
      version: 1,
      contentType: 'text/plain',
      tags: [
        { name: 'physics', category: 'topic' },
        { name: 'superconductor', category: 'type' },
        { name: 'replication', category: 'methodology' },
        { name: 'unverified', category: 'type' },
        { name: 'materials', category: 'type' },
        { name: 'critical', category: 'urgency' }
      ],
    },
    status: 'flagged',
    votes: 1876,
    comments: 432,
    author: 'anon-physics1',
    updated: '1d ago',
    walrusBlobId: undefined,
    contentHash: undefined,
  },
  {
    id: 'graphene-applications-18',
    title: 'Graphene electronics face manufacturing challenges despite superior properties',
    summary: 'Single-layer graphene shows exceptional electrical properties but lacks viable mass production methods for electronics.',
    fullContent: 'Graphene demonstrates outstanding electrical conductivity, mechanical strength, and thermal properties. However, industrial applications in electronics remain limited by difficulties in producing large-area, defect-free films and opening a suitable band gap for transistor applications.',
    sources: ['https://www.nature.com/articles/s41578-019-0159-3', 'https://doi.org/10.1038/s41578-019-0159-3'],
    metadata: {
      created: new Date('2024-07-22T15:45:00Z'),
      lastModified: new Date('2024-07-22T15:45:00Z'),
      version: 1,
      contentType: 'text/plain',
      tags: [
        { name: 'physics', category: 'topic' },
        { name: 'materials', category: 'topic' },
        { name: 'graphene', category: 'type' },
        { name: 'electronics', category: 'type' },
        { name: 'manufacturing', category: 'type' },
        { name: 'review', category: 'type' }
      ],
    },
    status: 'review',
    votes: 567,
    comments: 89,
    author: 'anon-materials1',
    updated: '1w ago',
    walrusBlobId: undefined,
    contentHash: undefined,
  },
  {
    id: 'fusion-energy-19',
    title: 'ITER project faces continued delays and cost overruns',
    summary: 'International fusion reactor construction delayed to 2034 with costs exceeding $20 billion.',
    fullContent: 'The International Thermonuclear Experimental Reactor (ITER) project has experienced significant delays and budget increases. First plasma now scheduled for 2034, 13 years behind original timeline. Total costs estimated at over $20 billion, raising questions about fusion energy timeline.',
    sources: ['https://www.iter.org/proj/inafewlines', 'https://www.nature.com/articles/d41586-021-02296-z'],
    metadata: {
      created: new Date('2024-08-12T11:15:00Z'),
      lastModified: new Date('2024-08-12T11:15:00Z'),
      version: 1,
      contentType: 'text/plain',
      tags: [
        { name: 'physics', category: 'topic' },
        { name: 'fusion', category: 'type' },
        { name: 'energy', category: 'type' },
        { name: 'iter', category: 'type' },
        { name: 'delays', category: 'type' },
        { name: 'critical', category: 'urgency' }
      ],
    },
    status: 'verified',
    votes: 1234,
    comments: 267,
    author: 'anon-fusion1',
    updated: '3d ago',
    walrusBlobId: undefined,
    contentHash: undefined,
  },

  // 🧠 Neuroscience Facts (2 facts)
  {
    id: 'brain-computer-interface-20',
    title: 'Neuralink demonstrates high-bandwidth brain-computer interface',
    summary: 'Paralyzed patients control computer cursor with 90% accuracy using implanted brain chips.',
    fullContent: 'Neuralink\'s brain-computer interface enabled paralyzed patients to control computer cursors and type at speeds up to 90 characters per minute. The system uses 1024 electrodes to record neural signals from motor cortex, processed by machine learning algorithms to decode intended movements.',
    sources: ['https://www.biorxiv.org/content/10.1101/2024.02.15.580459v1', 'https://neuralink.com/science/'],
    metadata: {
      created: new Date('2024-08-18T13:20:00Z'),
      lastModified: new Date('2024-08-18T13:20:00Z'),
      version: 1,
      contentType: 'text/plain',
      tags: [
        { name: 'neuroscience', category: 'topic' },
        { name: 'bci', category: 'type' },
        { name: 'neuralink', category: 'type' },
        { name: 'paralysis', category: 'type' },
        { name: 'motor-cortex', category: 'type' },
        { name: 'experimental', category: 'methodology' }
      ],
    },
    status: 'review',
    votes: 987,
    comments: 234,
    author: 'anon-neuro1',
    updated: '2d ago',
    walrusBlobId: undefined,
    contentHash: undefined,
  },
  {
    id: 'memory-consolidation-21',
    title: 'Sleep replay strengthens memory consolidation in hippocampus',
    summary: 'Neural recordings show hippocampal sharp-wave ripples replay daily experiences during slow-wave sleep.',
    fullContent: 'Hippocampal sharp-wave ripples during non-REM sleep replay compressed versions of daily experiences at 20x normal speed. This replay strengthens synaptic connections and transfers memories from hippocampus to neocortex for long-term storage, explaining why sleep is crucial for memory consolidation.',
    sources: ['https://www.science.org/doi/10.1126/science.aax0758', 'https://doi.org/10.1126/science.aax0758'],
    metadata: {
      created: new Date('2024-07-14T16:10:00Z'),
      lastModified: new Date('2024-07-14T16:10:00Z'),
      version: 1,
      contentType: 'text/plain',
      tags: [
        { name: 'neuroscience', category: 'topic' },
        { name: 'memory', category: 'type' },
        { name: 'sleep', category: 'type' },
        { name: 'hippocampus', category: 'type' },
        { name: 'consolidation', category: 'type' },
        { name: 'peer-reviewed', category: 'methodology' }
      ],
    },
    status: 'verified',
    votes: 678,
    comments: 145,
    author: 'anon-sleep1',
    updated: '2w ago',
    walrusBlobId: undefined,
    contentHash: undefined,
  }
];
